// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MinersConnection struct {
	PageInfo   *PageInfo     `json:"pageInfo"`
	Edges      []*MinersEdge `json:"edges"`
	TotalCount *int          `json:"totalCount"`
	Miners     []*Miner      `json:"miners"`
}

type MinersEdge struct {
	Node   *Miner `json:"node"`
	Cursor string `json:"cursor"`
}
